### ISSUE TITLE
"Without" does not seem to work properly

### ISSUE THREAD

**Issue by Stmated** [NSSTC/sim-ecs#18]
In system.ts there is this code:

```
if (!entity.hasComponent(accessStruct[access].component) || accessStruct[access].type == EAccess.UNSET) {
    return false;
}
```

But should this not be:

```
if (accessStruct[access].type == EAccess.UNSET) {
    if (entity.hasComponent(accessStruct[access].component)) {
        return false;
    }
} else {
    if (!entity.hasComponent(accessStruct[access].component)) {
        return false;
    }
}
```

Or the shorter:
```
if (entity.hasComponent(accessStruct[access].component) == (accessStruct[access].type == EAccess.UNSET)) {
    return false;
}
```

Since as things stand right now it will always check if it has the component and then return false if it does not.

**Comment by minecrawler** [comment]
Thank you for reporting this problem! I am a bit busy at work and with my life right now, so I might need a few days to take a look at it. We need a some test cases and then we can fix the code. I will be able to do so in a few days, however I also welcome PRs :)

**Comment by minecrawler** [comment]
Had time sooner than anticipated and got rid of some code duplication while at it. It should now work and the checking part (in entity.ts) is now tested.
