### ISSUE TITLE
The runtime world hasn't initialized a scheduler executor!

### ISSUE THREAD

**Issue by jpraccio0722** [NSSTC/sim-ecs#73]
Saw the above exception when trying this library out. 
Ran the examples included in the repo and received the same error.
Seems that currentSchedulerExecutor is undefined in the runtime-world.
Currently there is no way to run the world.

**Comment by minecrawler** [comment]
Thank you for your report. What version are you using? What's your runtime?

**Comment by minecrawler** [comment]
@jpraccio0722 I released a hotfix: v0.6.4. It should be working, now. Please run `npm install` after switching to the new version.
